Add user management operations
BjoernPetersen/MusicBot-API pull request #23
Opened 2020-11-10 16:00 UTC by FelixGail

Adds user and permission management (#21)

I am personally unhappy with  `operationId: deleteDifferentUser`, but I don't want to break existing implementations by renaming `deleteUser`.

2020-11-10 19:58 UTC, BjoernPetersen requested changes

2020-11-10 19:58 UTC, BjoernPetersen commented on MusicBot.yaml
> +        PAUSE -> Allows pausing the playback;
and resuming

2020-11-10 19:58 UTC, BjoernPetersen commented on MusicBot.yaml
> +        SKIP -> Allows skipping songs;
From [Permission.kt](https://github.com/BjoernPetersen/MusicBot/blob/develop/src/main/kotlin/net/bjoernpetersen/musicbot/api/auth/Permission.kt) (Linked in the README.md): 

> The permission to skip the current song or remove songs from the queue.
> Note that a user is always allowed to remove a song from the queue which he added himself.

2020-11-10 19:58 UTC, BjoernPetersen commented on MusicBot.yaml
> +        ALTER_SUGGESTIONS -> Enquing a song while holding this permission will give feedback to suggesters
"enqueuing" or "enqueueing"

2020-11-10 19:58 UTC, BjoernPetersen commented on MusicBot.yaml
> +        USER -> Allows deleting or altering other users and their permissions;
This one should probably called `ADMIN`. Having the permission should NOT include the other permissions, but it effectively makes the user an admin as he is allowed to alter his own permissions.

2020-11-10 19:58 UTC, BjoernPetersen commented on MusicBot.yaml
> +          description: The user to retrieve
Note that it's case-insensitive

2020-11-10 19:58 UTC, BjoernPetersen commented on MusicBot.yaml
> +      summary: Set a users permissions
```suggestion
      summary: Set a user's permissions
```

2020-11-10 19:58 UTC, BjoernPetersen commented on MusicBot.yaml
> +        Updates a users permissions.
```suggestion
        Updates a user's permissions.
```

2020-11-10 19:58 UTC, BjoernPetersen commented on MusicBot.yaml
> +      operationId: setUserPermissions
This operation should probably be done on `/user/{username}/permission` as it's only updating a subset of the user (his permissions).

2020-11-11 09:50 UTC, FelixGail commented on MusicBot.yaml
> +        USER -> Allows deleting or altering other users and their permissions;
Do you think it is sensible to change this behaviour? For example, a user could only assign authorisations that he or she owns.

I think calling it admin could be misleading in this situation

2020-11-11 10:02 UTC, BjoernPetersen commented on MusicBot.yaml
> +        USER -> Allows deleting or altering other users and their permissions;
Only allowing a user to give permissions they own themselves seems like a good idea, I'm fine with that.

2020-11-11 10:08 UTC, BjoernPetersen requested changes

2020-11-11 10:08 UTC, BjoernPetersen commented on MusicBot.yaml
> +        The update will reach the user, when he updates his JWT token.
I think that's a very German comma

```suggestion
        The update will reach the user when he updates his JWT token.
```

2020-11-11 10:08 UTC, BjoernPetersen commented on MusicBot.yaml
> +    delete:
This operation should be moved up, it's on the wrong path now (`/user/{username}/permission`)

2020-11-11 10:51 UTC, FelixGail commented on MusicBot.yaml
> +        USER -> Allows deleting or altering other users and their permissions;
Should I still change `USER` to `ADMIN` or is the name acceptable, with this change?

2020-11-11 11:13 UTC, BjoernPetersen requested changes

2020-11-11 11:13 UTC, BjoernPetersen commented on MusicBot.yaml
> +        USER -> Allows deleting or altering other users and their permissions;
I wouldn't name it `ADMIN` then, but a more descriptive name would still be nice. All other permission names describe some kind of action, `USER` doesn't really convey what actions it allows.

2020-11-11 11:13 UTC, BjoernPetersen commented on MusicBot.yaml
> +      operationId: deleteDifferentUser
I'm also not that happy with this operation ID. Maybe `deleteOtherUser`?

2020-11-11 11:13 UTC, BjoernPetersen commented on MusicBot.yaml
> +        Permission information about users reflects the current state of the bot, permissions saved in still valid jwt tokens may vary.
```suggestion
        Permission information about users reflects the current state of the bot, permissions saved in still valid JWT tokens may vary.
```

2020-11-11 11:13 UTC, BjoernPetersen commented on MusicBot.yaml
> +        - USER
These should all be lower case as that's the value actually transmitted via the API (see `label` in [Permissions.kt](https://github.com/BjoernPetersen/MusicBot/blob/develop/src/main/kotlin/net/bjoernpetersen/musicbot/api/auth/Permission.kt))

2020-11-11 12:43 UTC, FelixGail commented on MusicBot.yaml
> +        USER -> Allows deleting or altering other users and their permissions;
`MANAGE_USERS`?

2020-11-11 14:44 UTC, BjoernPetersen commented on MusicBot.yaml
> +        USER -> Allows deleting or altering other users and their permissions;
Yeah, that's nice enough.

2020-11-13 09:00 UTC, BjoernPetersen requested changes
The operation descriptions should mention the required permission ("manage_users").

Do you think it might be problematic to effectively allow users to impersonate another user by deleting and recreating them? Maybe that should be a separate permission.

How do we handle attempts to change permissions of a user with more permission than the managing user? E.g.:

```
userA.permissions = [manage_users, skip, pause]
userB.permissions = [skip, pause, dislike, move, enqueue, alter_suggestions]
userA.setPermissions(userB, [skip, pause])
// What are userB's permissions now? Just skip and pause?
```

2020-11-13 09:54 UTC, FelixGail commented
> Do you think it might be problematic to effectively allow users to impersonate another user by deleting and recreating them? Maybe that should be a separate permission.

This is indeed problematic. I think a separate permission for user deletions is the most straightforward change.

> How do we handle attempts to change permissions of a user with more permission than the managing user? E.g.:
> ```
> userA.permissions = [manage_users, skip, pause]
> userB.permissions = [skip, pause, dislike, move, enqueue, alter_suggestions]
> userA.setPermissions(userB, [skip, pause])
> // What are userB's permissions now? Just skip and pause?
> ```

Do you think this could be solved by allowing a user to only **change** those permissions he owns? In the above example `userA` would only be able to bestow the `skip` and `pause` onto `userB`, but not remove any of the permissions he doesn't own.

I intentionally skipped  the `manage_users` permission in the above example, because if we handle permissions this way this permission needs to be separately. Otherwise we would create a new loophole, where `userA` gives `userB` the `manage_users` permission who in turn can bestow all of his permissions.

I can think of three possible solutions:

- _The Teamspeak way:_ We could add a new admin permission
- We change the `manage_users` permission to an `admin` permission, giving the user all other permissions implicitly
- In order to bestow the `manage_users` permission a user needs all other pemissions

2020-11-13 10:04 UTC, BjoernPetersen commented
> Otherwise we would create a new loophole, where userA gives userB the manage_users permission who in turn can bestow all of his permissions.

I don't think that's a loophole, really. Users who are given the `manage_users` permission may give that permissions to other users, but they could only escalate their own permissions by that if the other user with more permissions colludes with them. I'd personally be fine with that risk.

> Do you think this could be solved by allowing a user to only change those permissions he owns? In the above example userA would only be able to bestow the skip and pause onto userB, but not remove any of the permissions he doesn't own.

That's a good approach, but I don't think it's enough. That limitation would still allow a user with `manage_users` permissions to remove certain permissions of any user, even the server owner who gave himself every possible permission.

It's a puzzler, really. This is going to need some time to think about it.

2020-11-13 11:02 UTC, BjoernPetersen commented
After some discussion with a flatmate of mine, I think the best solution is making the `manage_users` permission an `admin` permission. The permission allows a user to grant or revoke any permissions for himself or other users.

When a user is granted the `admin` permission he is automatically granted all other permissions. If more possible permissions are added to the system later on, they'll have to be granted manually.

While the `admin` permission allows the user to escalate their own permissions, it doesn't in itself include any other permission, i.e. a user with the `admin` permission but without the `enqueue` permission will not be able to enqueue songs.

To prevent "coups", I suggest the following limitation:
An admin can not edit the permissions of another admin, except for his own. Removing admins will thus not be possible via the API, although admins may step down of course.

2020-11-14 14:11 UTC, FelixGail commented
FYI: The editorconfig check runs through, but the check is running on the fork somehow: https://github.com/FelixGail/MusicBot-API/actions/runs/363214297

2020-11-14 20:19 UTC, BjoernPetersen commented
Sorry about that. Updating your branch should fix the problem.

2020-11-15 13:08 UTC, BjoernPetersen commented
Okay, I really want to merge this branch. I do have one more idea though. It's kind of a rehash of some of our ideas to the current solution:

## Introduce a `manage_admins` permission

Introducing this permission would allow almost all user management to be done via the API.

### Granted rights

- Grant and revoke the `admin` permission
- Grant, but **not revoke** the `manage_admins` permission 
  - Analogously to the previous approach for admins
  - The revocation aspect limits the API a bit, but prevents "coups". I'm not sure about it yet, so input is welcome.

### Changes to `admin`

- Users with the `admin` permission can not add new admins anymore
- Making a user admin doesn't grant him the `manage_admins` permission

### Benefits

- Appointing an admin temporarily is much more viable
  - Removing the `admin` permission of a user doesn't leave him a time window in which he could re-add the permission with the existing JWT
- "Rogue" admins can't do as much damage
- The `manage_admins` permission can be reserved for especially trusted users (maybe the server owner even completely reserves it for himself)
  - This is what makes me doubt the `manage_admin` revocation limitation

2020-11-15 13:08 UTC, BjoernPetersen commented
Additionally, we should add a limitation to the `deleteOtherUser` operation: Only non-admins may be deleted.

2020-11-15 13:51 UTC, FelixGail commented
> Introduce a manage_admins permission

That's a nice solution

>     * The `manage_admins` permission can be reserved for especially trusted users (maybe the server owner even completely reserves it for himself)
>       
>       * This is what makes me doubt the `manage_admin` revocation limitation

I don't think this restriction is needed. Not having it could even proof beneficial as unused accounts could be removed over the API.
To match the intention of this permission it could be named `OWNER`, setting as guideline that all users with this permission should be able to access the bot directly anyway.

2020-11-15 14:42 UTC, BjoernPetersen commented
Yeah, I also toyed with `superuser`, but `owner` is probably most obvious.

2020-11-16 09:17 UTC, BjoernPetersen requested changes

2020-11-16 09:17 UTC, BjoernPetersen commented on MusicBot.yaml
> +        201:
```suggestion
        204:
```

`201` is "Created"

2020-11-16 09:17 UTC, BjoernPetersen commented on MusicBot.yaml
> +        201:
```suggestion
        204:
```

2020-11-16 09:17 UTC, BjoernPetersen commented on MusicBot.yaml
> +          Granting a user the admin permission will automatically grant him all other current permissions.
```suggestion
          Granting a user the admin permission will automatically grant him all other current permissions except OWNER.
```

2020-11-16 09:17 UTC, BjoernPetersen commented on MusicBot.yaml
> +          Users holding the admin permission can not alter the permissions of other admins;
```suggestion
          Users holding the admin permission can not alter the permissions of or delete other admins;
```

2020-11-16 09:20 UTC, BjoernPetersen commented
The docs should also mention that admins (not owners) can't give others the ADMIN permission.

2020-11-16 10:10 UTC, BjoernPetersen commented on MusicBot.yaml
> +        OWNER -> Allows altering permissions or deleting users holding the ADMIN or OWNER permission.
```suggestion
        OWNER -> Allows granting the ADMIN permission, altering permissions of admins and owners or deleting ADMIN or OWNER users.
```

2020-11-16 10:11 UTC, BjoernPetersen approved these changes

2020-11-16 10:12 UTC, BjoernPetersen commented on MusicBot.yaml
> +        OWNER -> Allows granting the ADMIN permission, altering permissions of admins and owners or deleting ADMIN or OWNER users.
```suggestion
        OWNER -> Allows granting the ADMIN permission, altering permissions of admins and owners or
          deleting ADMIN or OWNER users.
```

2020-11-16 10:14 UTC, merged

2020-11-16 10:15 UTC, BjoernPetersen commented
Thanks for your contribution!